### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by sh1ng** [jaredhoberock/bulk#46]
Hi!

First of all  thank you so much for creating that library. 

I'm curious what is the status of it. I've seen the same code in the Thrust.  Will all upcoming development be there(with extended support for async)?

**Comment by jaredhoberock** [comment]
Hi sh1ng,
Bulk isn't being actively developed right now. You might be interested in [Agency](https://github.com/jaredhoberock/agency), which has superseded much of the functionality in Bulk.

**Comment by sh1ng** [comment]
But how is it related to Thrust?

**Comment by jaredhoberock** [comment]
It's not related to Thrust at all at the moment. It's the sort of lower-level library one might use to create a library such as Thrust.
